### ISSUE TITLE
print comes with extra new line

### ISSUE THREAD

**Issue by akhodeir** [abdo-Turkii/School-Database-Project#6]
please remove all new line that comes when we use t option

**Comment by abdo-Turkii** [comment]
hello,
Print top 10  like in image deal or not .
![Screenshot 2024-08-06 130210](https://github.com/user-attachments/assets/99977a86-4cc6-48b8-bcf8-504295fad61f)
Thanks.

**Comment by PashMohandes** [comment]
Please add the rank in the beginning if the line not the end.

Please remove the empty lines

**Comment by abdo-Turkii** [comment]
hi,
The format of the printing has been updated based on your requirements
![image](https://github.com/user-attachments/assets/c9986fce-a478-41b1-af26-cbbaddd01ea7)
Thanks.
